---
title: ' Consumers’ active choice behavior promotes stable eco-evolutionary units'
author: Allan Alvarenga
date: '2020-03-08'
slug: active_choice
categories:
  - Ecology
tags:
  - Community ecology
  - Ecological networks
  - Animal behaviour
summary: ''
authors: []
external_link: ''
image:
  caption: ''
  focal_point: ''
  preview_only: no
url_code: ''
url_pdf: ''
url_slides: ''
url_video: ''
slides: ''
---

Individual behavior, interaction mechanisms, temporal organization, and local context are processes that can influence the structure and evolution of ecological interactions. In trophic interactions, consumers can increase their fitness by actively choosing resources that enhance their chances of exploring them successfully. Upon searching for potential resources, they are able to decide which one to choose according to their value and maneuverability. Mathematical modeling is often employed in theoretical studies to understand the coevolutionary dynamics between these species. However, they often disregard the individual consumer behavior since the complexity of these systems usually requires simplifying assumptions about interaction details. Here we show that active consumer choice can generate stable ecological and coevolutionary units over time. The phenotype of both consumers and resources converge into multiple groups densely connected within themselves, exerting reciprocal selective pressure between them. The species preferentially interact with specific modules in the networks, separated by differences in their fundamental niches, depending on the size and composition of the interaction neighborhoods. Network metrics did not follow a single trend. However, there was no correlation with the coevolutionary pressure intensity imposed by consumers' behavior. Our results demonstrate that explicit modeling of active consumer choice generates congruent coevolutionary dynamics and interaction structures. They generate higher amplitudes on network metrics that more closely match empirical networks than models that disregard this aspect of behavior. Thus, we consider that the inclusion of consumers' active choice behavior plays an important role in the ecological and evolutionary processes that structure these communities.
